// <auto-generated />
using System;
using Infrastructure.Repository.Generics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WC.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WC.Infra.Data.Entities.ImagemProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProdutoEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Update_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoEntityId");

                    b.ToTable("ImagensProduto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9f3de3b-54fc-42af-8b57-bb1390f6ac86"),
                            Create_At = new DateTime(2021, 9, 19, 9, 48, 34, 227, DateTimeKind.Local).AddTicks(9090),
                            Name = "Rafael",
                            Update_At = new DateTime(2021, 9, 19, 9, 48, 34, 228, DateTimeKind.Local).AddTicks(7788),
                            Url = "rafael.angelo@gmail.com"
                        });
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EstoqueQuantidade")
                        .HasColumnType("real");

                    b.Property<int>("MediaAvaliacao")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.Property<float>("PrecoPromocional")
                        .HasColumnType("real");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.RotaRamificadaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RotaSementeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Update_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasScraping")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RotaSementeEntityId");

                    b.ToTable("RotasRamificada");
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.RotaSementeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pesquisa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotasSemente");
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.ImagemProdutoEntity", b =>
                {
                    b.HasOne("WC.Infra.Data.Entities.ProdutoEntity", null)
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoEntityId");
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.RotaRamificadaEntity", b =>
                {
                    b.HasOne("WC.Infra.Data.Entities.RotaSementeEntity", null)
                        .WithMany("RotasRamificadas")
                        .HasForeignKey("RotaSementeEntityId");
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.ProdutoEntity", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("WC.Infra.Data.Entities.RotaSementeEntity", b =>
                {
                    b.Navigation("RotasRamificadas");
                });
#pragma warning restore 612, 618
        }
    }
}
